### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by elrasool** [google-developer-training/android-basics-kotlin-unscramble-app#126]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
I think the main problem method getNextWord()

**Describe the problem**

After going step by step after the code lab of Store data in ViewModel, I have an error which talking about referring a null reference error, like the message error below
" Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
        at com.example.android.unscramble.ui.game.GameViewModel.getNextWord(GameViewModel.kt:36)
        at com.example.android.unscramble.ui.game.GameViewModel.<init>(GameViewModel.kt:9)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.android.unscramble.ui.game.GameFragment.getViewModel(GameFragment.kt:33)
        at com.example.android.unscramble.ui.game.GameFragment.updateNextWordOnScreen(GameFragment.kt:129)
        at com.example.android.unscramble.ui.game.GameFragment.onViewCreated(GameFragment.kt:61)
"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio Arctic | 2020.3.1 Patch 2
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![viewmodelcodelab](https://user-images.githubusercontent.com/13761393/136524399-f747befe-d5b4-463c-b475-4a070ea05139.jpg)

**Comment by elrasool** [comment]
Any update to continue my learning? @DAGalpin

**Comment by duemoselund** [comment]
Apparently, you need to move the init block below the variables - I stumbled upon the same error, and turns out the initialization of the variables and the init block happens in the same order they were positioned in the class body. This was not apparent from the examples in the guide.
