### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by AryanvGupta** [google-developer-training/android-basics-kotlin-unscramble-app#91]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#8 

**In which task and step of the codelab can this issue be found?**
Store data in ViewModel --> 7. Populate ViewModel --> after creating 'private fun getNextWord()'

**Describe the problem**
The app crashes and shows a runtime error in Logcat.
There is a null value being detected which is causing the crash

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  4.2.1
_API version of the emulator:_  24 (android 7)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Text and image form of the logcat

2021-07-02 19:09:04.835 26786-26786/? I/art: Late-enabling -Xcheck:jni
2021-07-02 19:09:04.905 26786-26786/com.example.android.unscramble W/System: ClassLoader referenced unknown path: /data/app/com.example.android.unscramble-2/lib/arm64
2021-07-02 19:09:04.969 26786-26786/com.example.android.unscramble W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2021-07-02 19:09:05.138 26786-26786/com.example.android.unscramble D/GameFragment: GameFragment created/re-created!
2021-07-02 19:09:05.139 26786-26786/com.example.android.unscramble D/GameFragment: GameViewModel created!
2021-07-02 19:09:05.142 26786-26786/com.example.android.unscramble D/AndroidRuntime: Shutting down VM
2021-07-02 19:09:05.143 26786-26786/com.example.android.unscramble E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.unscramble, PID: 26786
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.unscramble/com.example.android.unscramble.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6321)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
        at com.example.android.unscramble.ui.game.GameViewModel.getNextWord(GameViewModel.kt:38)
        at com.example.android.unscramble.ui.game.GameViewModel.<init>(GameViewModel.kt:9)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.android.unscramble.ui.game.GameFragment.getViewModel(GameFragment.kt)
        at com.example.android.unscramble.ui.game.GameFragment.updateNextWordOnScreen(GameFragment.kt:131)
        at com.example.android.unscramble.ui.game.GameFragment.onViewCreated(GameFragment.kt:63)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1322)
        at android.app.Activity.performStart(Activity.java:6777)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6321) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
2021-07-02 19:09:05.143 26786-26786/com.example.android.unscramble D/AppTracker: App Event: crash
2021-07-02 19:09:05.166 26786-26786/? I/Process: Sending signal. PID: 26786 SIG: 9

![Screenshot (963)](https://user-images.githubusercontent.com/55129067/124284990-22fe3200-db6b-11eb-9b8b-517d6e74a6d9.png)
![Screenshot (964)](https://user-images.githubusercontent.com/55129067/124284995-242f5f00-db6b-11eb-8cca-20bdb522e306.png)

**Comment by thekuom** [comment]
It's not clear that the `init` block needs to be after the variables since in "The lifecycle of a ViewModel", this code block is shown, implying that the `init` block should be the first thing in the class
![image](https://user-images.githubusercontent.com/15683724/124617287-6f33c580-de3c-11eb-8158-ec91895a7acd.png)
